Separate out privup init from main functionality
Signed-off-by: Tyler Heucke <tyler@heucke.io>

diff --git a/bin/privup b/bin/privup
--- a/bin/privup
+++ b/bin/privup
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
-
 set -euo pipefail
-
 # set -x
 
 [[ $# -lt 3 ]] && {
@@ -13,16 +11,6 @@ key_file="$1"; shift
 dist="$1"; shift
 files=( "$@" )
 
-while true; do
-  running_builds="$(curl -ns --anyauth 'https://api.buildkite.com/v2/builds?state=running' | jq 'length')"
-  if [[ "$running_builds" -gt 0 ]]; then
-    echo "Error: $running_builds builds are currently running. Sleeping 5 seconds and trying again." >&2
-    sleep 5
-  else
-    break
-  fi
-done
-
 instance_ip="$(aws ec2 describe-instances --filters "Name=tag:BuildkiteQueue,Values=aptly" --query 'Reservations[0].Instances[0].PublicIpAddress' | cut -d'"' -f2)"
 
 ssh_aws() {
@@ -30,40 +18,76 @@ ssh_aws() {
   ssh -o "StrictHostKeyChecking no" -i "$key_file" "ec2-user@$instance_ip" "sudo -u buildkite-agent -i bash -c '$*'"
 }
 
+init() {
+  if [[ ! -e "$key_file" ]]; then
+    echo "Key file $key_file not found." >&2
+    return 1
+  fi
+
+  if ! ssh_aws test -e '.aws/config' >/dev/null; then
+    echo "AWS credentials not present on agent." >&2
+    return 1
+  fi
+
+  printf "[INFO] Waiting for builds to finish" >&2
+
+  while true; do
+    running_builds="$(curl -ns --anyauth 'https://api.buildkite.com/v2/builds?state=running' | jq 'length')"
+    if [[ "$running_builds" -gt 0 ]]; then
+      printf "." >&2
+      sleep 5
+    else
+      printf " done!\\n" >&2
+      break
+    fi
+  done
+
+  trap cleanup EXIT
+
+  ssh_aws sudo service buildkite-agent-1 stop
+
+  ssh_aws aws s3 sync --delete s3://aptly.openswitch.net/ /aptly
+}
+
 cleanup() {
+  set +e
   ssh -o "StrictHostKeyChecking no" -i "$key_file" "ec2-user@$instance_ip" 'sudo rm -rf /privup/'
   ssh_aws /usr/local/bin/aptly db cleanup
   ssh_aws aws s3 sync --delete /aptly s3://aptly.openswitch.net/
-}
-trap cleanup EXIT
-
-ssh_aws ls -l '.aws/credentials' >/dev/null || {
-  echo "AWS credentials not present on agent." >&2
-exit 1
+  ssh_aws sudo service buildkite-agent-1 start
+  set -e
 }
 
-ssh -o "StrictHostKeyChecking no" -i "$key_file" "ec2-user@$instance_ip" 'sudo mkdir -p /privup/'
-ssh -o "StrictHostKeyChecking no" -i "$key_file" "ec2-user@$instance_ip" 'sudo chmod -R a+rwx /privup/'
-rsync -Pav -e "ssh -o \"StrictHostKeyChecking no\" -i $key_file" "${files[@]}" "ec2-user@$instance_ip:/privup/"
-echo "Adding packages: $(ssh_aws ls '/privup/')"
+main() {
+  ssh -o "StrictHostKeyChecking no" -i "$key_file" "ec2-user@$instance_ip" 'sudo mkdir -p /privup/'
+  ssh -o "StrictHostKeyChecking no" -i "$key_file" "ec2-user@$instance_ip" 'sudo chmod -R a+rwx /privup/'
+  rsync -Pav -e "ssh -o \"StrictHostKeyChecking no\" -i $key_file" "${files[@]}" "ec2-user@$instance_ip:/privup/"
+  echo "Adding packages: $(ssh_aws ls '/privup/')"
 
-ssh_aws aws s3 sync --delete s3://aptly.openswitch.net/ /aptly
-if [[ "$dist" == "jessie" ]]; then
-  ssh_aws /usr/local/bin/aptly repo add "opx-non-free" '/privup/'
-  ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:"
-  ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:"
-  ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:"
-  ssh_aws /usr/local/bin/aptly publish update 2-updates "s3:opx:"
-  ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:$dist"
-  ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:$dist"
-  ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:$dist"
-  ssh_aws /usr/local/bin/aptly publish update 2-updates "s3:opx:$dist"
-else
-  ssh_aws /usr/local/bin/aptly repo add "opx-non-free-$dist" '/privup/'
-  ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:$dist"
-  ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:$dist"
-  ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:$dist"
-  if [[ "$dist" == "stretch" ]]; then
-    ssh_aws /usr/local/bin/aptly publish update 3-updates "s3:opx:$dist"
+  if [[ "$dist" == "jessie" ]]; then
+    ssh_aws /usr/local/bin/aptly repo add "opx-non-free" '/privup/'
+    ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:"
+    ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:"
+    ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:"
+    ssh_aws /usr/local/bin/aptly publish update 2-updates "s3:opx:"
+    ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:$dist"
+    ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:$dist"
+    ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:$dist"
+    ssh_aws /usr/local/bin/aptly publish update 2-updates "s3:opx:$dist"
+  else
+    ssh_aws /usr/local/bin/aptly repo add "opx-non-free-$dist" '/privup/'
+    ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:$dist"
+    ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:$dist"
+    ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:$dist"
+    if [[ "$dist" == "stretch" ]]; then
+      ssh_aws /usr/local/bin/aptly publish update 3-updates "s3:opx:$dist"
+    fi
   fi
+}
+
+if init; then
+  main
+else
+  echo "[ERROR]: Failed to initialize" >&2
+  exit 1
 fi
