Wait until builds are finished before publishing
Signed-off-by: Tyler Heucke <tyler.heucke@dell.com>

diff --git a/bin/privup b/bin/privup
--- a/bin/privup
+++ b/bin/privup
@@ -2,7 +2,7 @@
 
 set -euo pipefail
 
-set -x
+# set -x
 
 [[ $# -lt 3 ]] && {
   echo "Usage: $0 <ssh-key-file> <debian-dist> <files>..." >&2
@@ -13,11 +13,15 @@ key_file="$1"; shift
 dist="$1"; shift
 files=( "$@" )
 
+while true; do
 running_builds="$(curl -ns 'https://api.buildkite.com/v2/builds?state=running' | jq 'length')"
 if [[ "$running_builds" -gt 0 ]]; then
-  echo "Error: $running_builds builds are currently running. Please wait for them to finish." >&2
-  exit 1
+  echo "Error: $running_builds builds are currently running. Sleeping 5 seconds and trying again." >&2
+  sleep 5
+else
+  break
 fi
+done
 
 instance_ip="$(aws ec2 describe-instances --filters "Name=tag:BuildkiteQueue,Values=aptly" --query 'Reservations[0].Instances[0].PublicIpAddress' | cut -d'"' -f2)"
 
@@ -44,6 +48,20 @@ rsync -Pav -e "ssh -i $key_file" "${files[@]}" "ec2-user@$instance_ip:/privup/"
 echo "Adding packages: $(ssh_aws ls '/privup/')"
 
 ssh_aws aws s3 sync --delete s3://aptly.openswitch.net/ /aptly
+if [[ "$dist" == "jessie" ]]; then
+ssh_aws /usr/local/bin/aptly repo add "opx-non-free" '/privup/'
+ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:"
+ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:"
+ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:"
+ssh_aws /usr/local/bin/aptly publish update 2-updates "s3:opx:"
+ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:$dist"
+ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:$dist"
+ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:$dist"
+ssh_aws /usr/local/bin/aptly publish update 2-updates "s3:opx:$dist"
+else
 ssh_aws /usr/local/bin/aptly repo add "opx-non-free-$dist" '/privup/'
-ssh_aws /usr/local/bin/aptly publish update unstable s3:opx:stretch
-ssh_aws /usr/local/bin/aptly publish update testing s3:opx:stretch
+ssh_aws /usr/local/bin/aptly publish update unstable "s3:opx:$dist"
+ssh_aws /usr/local/bin/aptly publish update testing "s3:opx:$dist"
+ssh_aws /usr/local/bin/aptly publish update stable "s3:opx:$dist"
+ssh_aws /usr/local/bin/aptly publish update 2-updates "s3:opx:$dist"
+fi
