Pretty up buildkite logs
Signed-off-by: Tyler Heucke <tyler.heucke@dell.com>

diff --git a/buildkite/tools_opx-py.yaml b/buildkite/tools_opx-py.yaml
--- a/buildkite/tools_opx-py.yaml
+++ b/buildkite/tools_opx-py.yaml
@@ -20,11 +20,12 @@ steps:
   - name: ":python: Format and Test"
     type: script
     command: |
+      echo "--- Installing dependencies"
       pipenv install --deploy --dev
       pipenv run pip install black
-      # Format
+      echo "--- Running formatter"
       DIFF="$(pipenv run black . --diff --quiet)"
-      [[ -n "$DIFF"  ]] && echo "Black failed.\n$DIFF" && exit 1
-      # Test
+      [[ -n "$DIFF"  ]] && echo "^^^ +++ Black failed.\n$DIFF" && exit 1
+      echo "+++ Testing"
       pipenv run pytest --cov=opx/ tests/ --cov-report=xml --cov-report=term
       bash <(curl -s https://codecov.io/bash)
